### ISSUE TITLE
Every() not starting right away

### ISSUE THREAD

**Issue by GreyEcologist** [recruit-lifestyle/AIRTimer#4]
Hey, I am missing something or is every() first starts after the time interval set? If so, could you make it start right away then repeat every interval instead?

**Comment by uny** [comment]
When you call every(), AIRTimer starts NSTimer as below:

``` swift
NSTimer.scheduledTimerWithTimeInterval(
    self.interval,
    target: actor,
    selector: "fire",
    userInfo: self.userInfo,
    repeats: true)
```

The behaviour is the same when you call `NSTimer.scheduledTimerWithTimeInterval`.
If needed, try this:

``` swift
func method() {
    ...
}
AIRTimer.every(duration) { _ in
    method()
}
method()
```
