### ISSUE TITLE
How could I know if the time is currently running or not

### ISSUE THREAD

**Issue by heshanlk** [recruit-lifestyle/AIRTimer#5]
How to know if the timer is currently active or not?. The invalidate seems doesn't set it to nil right?. So how to check the active and not active timers?

If two timers are running, how to really switch to one or other?

```
        if((exerciseTimer) == nil){
            restTimer.restart()
        }
        if((restTimer) == nil){
            exerciseTimer.restart()
        }
```

This code doesn't seems to work. it restart both.

**Comment by uny** [comment]
`AIRTimer` has `valid` to check if the timer is active or not.

```
let timer = AIRTimer.every(5) { _ in
    ...
}
print(timer.valid) // true
timer.invalidate()
print(timer.valid) // false
```

Can this property satisfy your need?

**Comment by heshanlk** [comment]
Question there is how can I know if the timer is active or not to restart it?. I have two timers in this case.

```
   let timer = AIRTimer.every(5) { _ in
       ...
   }

   let timer2 = AIRTimer.every(5) { _ in
       ...
   }
```

```
@IBAction func pauseTimer(sender: UIButton) {
    if(sender.titleLabel?.text == "Pause"){
        sender.setTitle("Resume", forState: .Normal)
        if(timer.valid){
            timer.invalidate()
        }
        else{
            timer2.invalidate()
        }
    }
    else {
        sender.setTitle("Pause", forState: .Normal)
        if(timer.valid){
            timer.restart()
        }
        else{
            timer2.restart()
        }
    }
}
```

this button action won't work, do you have any idea how to get this work?

**Comment by uny** [comment]
I think your IBAction is meaningless.
when you touch up inside `Pause` button, which timer do you want to pause?
when you touch up inside `Resume` button, which timer do you want to resume?

what is the difference between `active` and `not to restart it`?

**Comment by uny** [comment]
ah, i see. you want to switch the active timer by turns, is it right?

**Comment by uny** [comment]
> ah, i see. you want to switch the active timer by turns, is it right?

then, the below view controller will satisfy your need.

``` swift
import UIKit
import AIRTimer

final class ViewController: UIViewController {
    private let timer0: AIRTimer = {
        let timer = AIRTimer.every(5) { _ in
            print("0.")
        }
        timer.invalidate()
        return timer
    }()
    private let timer1: AIRTimer = {
        let timer = AIRTimer.every(5) { _ in
            print("1.")
        }
        return timer
    }()

    @IBAction func toggleTimer(sender: UIButton) {
        if self.timer0.valid {
            sender.setTitle("Resume", forState: .Normal)
            self.timer0.invalidate()
            self.timer1.restart()
        } else {
            sender.setTitle("Pause", forState: .Normal)
            self.timer0.restart()
            self.timer1.invalidate()
        }
    }
}
```

**Comment by heshanlk** [comment]
Thanks, I'll give it a try.

**Comment by uny** [comment]
@heshanlk 
feel free to reopen this issue if necessary.

**Comment by heshanlk** [comment]
I still can't pause both timers at the same time and start just one. When I invalidate both at the same time and try to check self.timer0.valid it gives me variable wrapping error, so that means it has no value. any idea?

**Comment by heshanlk** [comment]
`fatal error: unexpectedly found nil while unwrapping an Optional value`

**Comment by heshanlk** [comment]
So I think `.valid` is not available.

**Comment by uny** [comment]
@heshanlk 
can i see your code?
